export const USUARIO_LOGUEADO = "USUARIO_LOGUEADO";
export const CLEAN_STATE_USER = "CLEAN_STATE_USER";
export const VIEW_HEADER_DASH = "VIEW_HEADER_DASH";
export const HIDE_MENU_DASH = "HIDE_MENU_DASH";
export const IS_LOGUED_USER = "IS_LOGUED_USER";

//Context Menu
export const TYPE_EDIT_PROFILE = "TYPE_EDIT_PROFILE";
export const TYPE_LANGUAGE_CURRENCY = "TYPE_LANGUAGE_CURRENCY";
export const TYPE_FEEDBACK = "TYPE_FEEDBACK";
export const TYPE_REFERFRIEND = "TYPE_REFERFRIEND";
export const TYPE_TERMSCONDITIONS = "TYPE_TERMSCONDITIONS";