export const USUARIO_LOGUEADO = "USUARIO_LOGUEADO";
export const CLEAN_STATE_USER = "CLEAN_STATE_USER";
export const VIEW_HEADER_DASH = "VIEW_HEADER_DASH";
export const HIDE_MENU_DASH = "HIDE_MENU_DASH";